# Trabajo en aula
### Yamil Ignacio Paz Sea

## Metodo Congruencial Aditivo

In [50]:
import numpy as np
x = np.array([65,89,98,3,69])
r = np.array([])
m = 10
n = 1000
for i in range(n):
    aux = (x[len(x)-1] + x[i]) % m
    x = np.append(x,aux)
    r = np.append(r,(aux/(m-1)))
print(x)
print(r)


[65 89 98 ...  1  9  4]
[0.44444444 0.33333333 0.11111111 0.44444444 0.33333333 0.77777778
 0.         0.11111111 0.55555556 0.88888889 0.55555556 0.55555556
 0.66666667 0.11111111 1.         0.44444444 1.         0.55555556
 0.66666667 0.55555556 1.         0.88888889 0.33333333 1.
 0.44444444 0.33333333 0.11111111 0.44444444 0.33333333 0.77777778
 0.         0.11111111 0.55555556 0.88888889 0.55555556 0.55555556
 0.66666667 0.11111111 1.         0.44444444 1.         0.55555556
 0.66666667 0.55555556 1.         0.88888889 0.33333333 1.
 0.44444444 0.33333333 0.11111111 0.44444444 0.33333333 0.77777778
 0.         0.11111111 0.55555556 0.88888889 0.55555556 0.55555556
 0.66666667 0.11111111 1.         0.44444444 1.         0.55555556
 0.66666667 0.55555556 1.         0.88888889 0.33333333 1.
 0.44444444 0.33333333 0.11111111 0.44444444 0.33333333 0.77777778
 0.         0.11111111 0.55555556 0.88888889 0.55555556 0.55555556
 0.66666667 0.11111111 1.         0.44444444 1.         0.5555

## Metodo congruencial mixto

In [17]:
import numpy as np

x = np.array([4])
r = np.array([])
a = 1
c = 8
m = 15
n = 5
for i in range(n):
    aux = ((a*x[i]) + c)
    nuevo = aux % m
    x = np.append(x,nuevo)
    r = np.append(r,(nuevo / m))

print("↓ Residuo ↓\n",x)
print("↓ Numeros aleatorios ↓\n",r)

↓ Residuo ↓
 [ 4 12  5 13  6 14]
↓ Numeros aleatorios ↓
 [0.8        0.33333333 0.86666667 0.4        0.93333333]
