# Ejercicio 12
El procedimiento para las transformaciones de Box Cox es diseñado para
determinar una transformación óptima para la variable dependiente mientras se
estima un modelo de regresión lineal. Es muy útil cuando la variabilidad de Y cambia
como una función de las variables explicativas. A menudo, una apropiada
transformación de la variable explicada estabiliza esta variabilidad y produce que
las desviaciones alrededor del modelo sean más normalmente distribuidas.
La clase de transformaciones consideradas son transformaciones de potencia definidas por:

𝑦∗ = (𝑦 + 𝜆2)^𝜆1

En la cual los datos son calculados en una potencia de 𝜆1 después de cambiarlo a una
cierta cantidad 𝜆2. Posteriormente, el parámetro de cambio de 𝜆2 se fija igual a 0. Esta
clase incluyen raíces cuadradas, logaritmos, recíprocos, y otras transformaciones comunes,
que dependen sobre una potencia

## Inciso A
Con base en el ejercicio 11 elegir las variables significativas y mediante
transformaciones Box Cox en la variable dependiente identificar el modelo adecuado
utilizando las transformaciones comunes

In [7]:
import numpy as np
import pandas as pd
import copy
import math

def listarBetas(array, msg):

    print(msg)

    for index, Beta in enumerate(array, start=1):

        print(f'Beta {index} => {Beta[0]}')

def getSCT(y, n):
    meany = y.sum()/n
    suma = 0
    for i in range(n):
        suma = suma+((y[i, 0]-meany)**2)
    return suma

def regMult(x, y, n, k, lam):
    xc = copy.copy(x)
    yc = copy.copy(y)
    for i in range(n):
        for j in range(k):
            if lam == 0:
                return 0, lam
            xc[i, j+1] = ((xc[i, j+1]**lam))/lam
    xt = xc.T
    xtx = xt*xc
    xtxi = np.linalg.inv(xtx)
    xtxixt = xtxi*xt
    beta = xtxixt*y
    lu = (xc*xtxi*xc.T)
    sce = (yc.T)*(np.identity(n)-lu)*yc
    unos = np.ones(n, order='C')
    cunos = unos.reshape((n, 1))
    cunost = unos.reshape((1, n))
    yest = xc*beta
    lunos = cunos*(1/n)*cunos
    if intercepto == 0:
        scr = (yc.T)*(lu)*yc
    else:
        scr = (yc.T)*(lu-lunos)*yc
    if intercepto == 0:
        den = sce/(n-k)
    else:
        den = sce/(n-k-1)
    num = scr/(k)
    print(den)
    t = float(den)*xtxi
    if intercepto == 1:
        k = k+1
    for i in range(k):
        cof = math.sqrt(float(t[i, i]))
        tstud = float(beta[i, 0])/cof
    rcuad = float(scr/getSCT(yc, n))
    return rcuad, beta

def generateLam(i, linf):
    lam = np.ones(num_variables)
    cont = 0
    while i > 0:
        lam[cont] = linf+((i % 21)*0.1)
        cont = cont+1
        i = int(i/21)
    return lam

num_variables = 3

intercepto = 1

rango = 10

max_iter = num_variables ** rango

lim_inf = -2
lim_sup = 2

delta_rango = 0.1

R = -10
data = pd.read_csv("data11.csv")
X = data.iloc[:,2:]
Y = data.iloc[:,1]
X = np.matrix(X)
Y = np.matrix(Y)
X = np.insert(X, 0, 1, axis=1)
print(X)
Y = Y.T
Y = Y * Y.T
# print(X)
# print(Y)

# Y = np.linalg.matrix_power(Y,2)
for i in range(num_variables):
    # lam = generateLam(i, lim_inf)
    lam = 2
    rcuadrado, cbeta = regMult(X, Y, len(X), num_variables, lam)
    if rcuadrado > R:
        betagan = cbeta
        R = rcuadrado
print("R^2 Multiple de Lambda ==>",R)
listarBetas(betagan, "")


[[1.0000e+00 3.9750e+02 4.2200e+01 5.0700e+01 7.8300e+01]
 [1.0000e+00 4.1330e+02 3.8100e+01 5.2000e+01 7.9200e+01]
 [1.0000e+00 4.3920e+02 4.0300e+01 5.4000e+01 7.9200e+01]
 [1.0000e+00 4.5970e+02 3.9500e+01 5.5300e+01 7.9200e+01]
 [1.0000e+00 4.9290e+02 3.7300e+01 5.4700e+01 7.7400e+01]
 [1.0000e+00 5.2860e+02 3.8100e+01 6.3700e+01 8.0200e+01]
 [1.0000e+00 5.6030e+02 3.9300e+01 6.9800e+01 8.0400e+01]
 [1.0000e+00 6.2460e+02 3.7800e+01 6.5900e+01 8.3900e+01]
 [1.0000e+00 6.6640e+02 3.8400e+01 6.4500e+01 8.5500e+01]
 [1.0000e+00 7.1780e+02 4.0100e+01 7.0000e+01 9.3700e+01]
 [1.0000e+00 7.6820e+02 3.8600e+01 7.3200e+01 1.0610e+02]
 [1.0000e+00 8.4330e+02 3.9800e+01 6.7800e+01 1.0480e+02]
 [1.0000e+00 9.1160e+02 3.9700e+01 7.9100e+01 1.1400e+02]
 [1.0000e+00 9.3110e+02 5.2100e+01 9.5400e+01 1.2410e+02]
 [1.0000e+00 1.0215e+03 4.8900e+01 9.4200e+01 1.2760e+02]
 [1.0000e+00 1.1659e+03 5.8300e+01 1.2350e+02 1.4290e+02]
 [1.0000e+00 1.3496e+03 5.7900e+01 1.2990e+02 1.4360e+02]
 [1.0000e+00 1

TypeError: only size-1 arrays can be converted to Python scalars